version: 2
updates:
  # Monitorar dependências npm/pnpm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "koeprefeito-team"
    assignees:
      - "koeprefeito-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "auto-merge"

  # Monitorar dependências específicas do web app
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    reviewers:
      - "koeprefeito-team"
    commit-message:
      prefix: "deps(web)"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "web"

  # Monitorar dependências do design system/UI
  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    reviewers:
      - "koeprefeito-team"
    commit-message:
      prefix: "deps(ui)"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "ui"

  # Monitorar dependências do banco de dados
  - package-ecosystem: "npm"
    directory: "/packages/database"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
    reviewers:
      - "koeprefeito-team"
    commit-message:
      prefix: "deps(database)"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "database"

  # Monitorar GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    reviewers:
      - "koeprefeito-team"
    commit-message:
      prefix: "ci"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "github-actions"

  # Monitorar Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
    reviewers:
      - "koeprefeito-team"
    commit-message:
      prefix: "docker"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"